# Generated by Django 3.1.1 on 2020-10-02 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0002_auto_20201002_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghostpost',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
